//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment3
{
    using System;
    using System.Collections.Generic;
    
    public partial class diamondinfo
    {
        public diamondinfo()
        {

        }
        public int Id { get; set; }
        public string color { get; set; }
        public string cut { get; set; }
        public string clarity { get; set; }
        public string carat { get; set; }
    }
}
